#!/usr/bin/env bash

# Copyright 2020  Shanghai Jiao Tong University (Authors: Chenda Li, Wangyou Zhang)
# Apache 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
set -e
set -u
set -o pipefail

log() {
    local fname=${BASH_SOURCE[1]##*/}
    echo -e "$(date '+%Y-%m-%dT%H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

help_message=$(cat << EOF
Usage: $0 [--mono <True/False>] [--min_or_max <min/max>] [--sample_rate <8k/16k>]
  optional argument:
    [--mono]: True (Default), False
    [--min_or_max]: min (Default), max
    [--sample_rate]: 8k (Default), 16k
EOF
)

. ./db.sh

wsj_full_wav=$PWD/data_dif_position/wsj0/wsj0_wav
# Path to the directory containing WHAM! noise
# (will download from the official site if not specified)
wham_noise=/net/midgar/work/nitsu/data/wsj/wham_noise
whamr_wav=$PWD/data_dif_position/whamr/2speakers
whamr_scripts=$PWD

other_text=data_dif_position/wsj/local/other_text/text
nlsyms=data_dif_position/nlsyms.txt
mono=False
min_or_max=min
sample_rate=8k


. utils/parse_options.sh

if [ $# -ne 0 ]; then
    echo "${help_message}"
    exit 1;
fi

if [ ! -e "${WSJ0}" ]; then
    log "Fill the value of 'WSJ0' of db.sh"
    exit 1
fi
if [ ! -e "${WSJ1}" ]; then
    log "Fill the value of 'WSJ1' of db.sh"
    exit 1
fi


### This part is for WHAMR!
### Download mixture scripts and create mixtures for 2 speakers
local/whamr_create_mixture_dif_position_dm.sh --mono ${mono} --min-or-max ${min_or_max} --sample-rate ${sample_rate} \
    ${wham_noise:+--wham_noise $wham_noise} \
    ${whamr_scripts} ${WSJ0} ${wsj_full_wav} \
    ${whamr_wav} || exit 1;

# The following datasets will be created:
# {tr,cv,tt}_mix_{both,clean}_{anechoic,reverb}_${min_or_max}_${sample_rate}
#
# Note:
#   - `both`: a mixture of speech1, speech2 and noise (for speech separation)
#   - `clean`: a mixture of speech1 and speech2 (for speech separation)
#   - Note: `single` is not generated by create_wham_from_scratch_dif_position_dm.py
local/whamr_data_prep_dif_position_dm.sh --min-or-max ${min_or_max} --sample-rate ${sample_rate} \
    ${whamr_scripts}/whamr_scripts ${whamr_wav} ${wsj_full_wav} || exit 1;


### Also need wsj corpus to prepare language information
### This is from Kaldi WSJ recipe
log "local/wsj_data_prep_dm.sh ${WSJ0}/??-{?,??}.? ${WSJ1}/??-{?,??}.?"
local/wsj_data_prep_dm.sh ${WSJ0}/??-{?,??}.? ${WSJ1}/??-{?,??}.?
log "local/wsj_format_data_dm.sh"
local/wsj_format_data_dm.sh


log "Prepare text from lng_modl dir: ${WSJ1}/13-32.1/wsj1/doc/lng_modl/lm_train/np_data/{87,88,89}/*.z -> ${other_text}"
mkdir -p "$(dirname ${other_text})"

# NOTE(kamo): Give utterance id to each texts.
zcat ${WSJ1}/13-32.1/wsj1/doc/lng_modl/lm_train/np_data/{87,88,89}/*.z | \
    grep -v "<" | tr "[:lower:]" "[:upper:]" | \
    awk '{ printf("wsj1_lng_%07d %s\n",NR,$0) } ' > ${other_text}


log "Create non linguistic symbols: ${nlsyms}"
cut -f 2- data_dif_position/wsj/train_si284/text | tr " " "\n" | sort | uniq | grep "<" > ${nlsyms}
cat ${nlsyms}
