init: xavier_uniform
max_epoch: 150
use_amp: false
batch_type: folded
batch_size: 4
num_workers: 4

preprocessor: rir
preprocessor_conf:
    speech_sample_rate: 8000
    rir_sample_rate: 8000
    rir_length: &rir_length 8000
    rir_target: reverberant
    rir_source_index: 0
    rir_mic_index: 0
    predict_all_sources: true
    predict_all_mics: false
    force_single_channel: true
    speech_segment: 32000
    rir_normalize: none
    rir_crop_mode: right
    rir_pad_mode: right

model_conf:
    normalize_variance: true

optim: adamw
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 1.0e-02
patience: 10
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 5
scheduler: warmupreducelronplateau
scheduler_conf:
    warmup_steps: 4000
    mode: min
    factor: 0.5
    patience: 3

encoder: stft
encoder_conf:
    n_fft: &n_fft 256
    hop_length: &hop_length 64

predictor: fla_tflocoformer
predictor_conf:
    rir_length: *rir_length
    num_sources: 2
    num_mics: 1
    n_layers: 4
    emb_dim: 96
    attention_dim: 96
    norm_type: rmsgroupnorm
    num_groups: 4
    tf_order: ft
    n_heads: 4
    flash_attention: false
    pos_enc: rope
    ffn_type:
        - swiglu_conv1d
        - swiglu_conv1d
    ffn_hidden_dim:
        - 128
        - 128
    conv1d_kernel: 8
    conv1d_shift: 1
    dropout: 0.0
    eps: 1.0e-5
    temporal_attn_type: gated_fla
    fla_p: 3
    fla_dwc_kernel: 7
    fla_use_rope: false
    pooling: mean
    hidden_dim: 256

criterions:
  - name: rir_multitask
    conf:
        mrstft_weight: 1.0
        l1_weight: 0.1
        corr_weight: 0.1
        window_sz:
            - 128
            - 256
            - 512
        hop_sz:
            - 32
            - 64
            - 128
        time_domain_weight: 0.1
        normalize_variance: false
        reduction: mean
    wrapper: pit
    wrapper_conf:
        weight: 1.0
        independent_perm: true
